Brandon edwards default prob bug fix
Open-Network-Insight/open-network-insight pull request #114
Opened 2016-10-27 21:47 UTC by brandon-edwards

Bug fix: Set the default values for probabilities of words not seen in training (conditioned on a given topic) and topics (conditioned on documents not seen in training) to be zero.

Since final scoring is performed in one location for dos and proxy (SuspiciousConnectsScoreFunction.scala) and another for net flow (FlowPostLDA.scala); this fix required changes to two separate files. The previously set probabilities were 1/#topics and 0.05 respectively for these files. These values were changed to 0.

2016-10-27 22:06 UTC, NathanSegerlind approved these changes

2016-10-27 22:53 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/SuspiciousConnectsScoreFunction.scala
> +      0.0d / topicCount
why divide by topicCount and not just use 0d?

2016-10-27 22:53 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/SuspiciousConnectsScoreFunction.scala
>      val uniformProb = Array.fill(topicCount) {
maybe "zeroProb" is a more appropriate name than uniformProb

2016-10-27 22:53 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/netflow/FlowPostLDA.scala
> +      val uniformProb = Array.fill(topicCount)(0.0d)
zeroProb seems like a more appropriate name

2016-11-02 23:54 UTC, brandon-edwards commented
I've committed new changes to fix the order of parameters being passed to FlowWordCreator in FlowSuspiciousConnectsModel.scala . I have now tested this code with all changes and get good results.

2016-11-03 19:16 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModel.scala
> +      val joinedDF = inDF.join(ipToTopicMixDF, inDF(SourceIP) === ipToTopicMixDF("ip"), "left_outer")
I think I named these variables, so it's not your fault Brandon...
but these variable names stink.   I am sorry. A variable name should tell us  what something is, not how it was computed (as that is redundant with the code... that is, "joinedDF is the dataframe you get by taking in the in dataframe and joining it with something else"

I suggest:

recordsWithSrcIPTopicMixes for joinedDF

and then

recordsWithTopicMixes for joinedDF2

sorry about that

2016-11-03 19:34 UTC, rabarona requested changes

2016-11-03 19:34 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowScoreFunction.scala
> +    /** A null value for srcTopicMix or dstTopicMix indicated the ip (source or dest respectively)
This comment is very helpful, maybe it should appear in SuspiciousConnectsScoreFunction.scala as well.

2016-11-03 19:34 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModel.scala
> +      val joinedDF = inDF.join(ipToTopicMixDF, inDF(SourceIP) === ipToTopicMixDF("ip"), "left_outer")
Agree

2016-11-03 19:34 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModel.scala
> +    val flowWordCreator = new FlowWordCreator(timeCuts, ibytCuts, ipktCuts)
Was this an existing error? Have we been passing the wrong parameters to FlowWordCreator all the time? Or did FlowWordCreator constructor changed?

2016-11-03 19:40 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModel.scala
> +    val flowWordCreator = new FlowWordCreator(timeCuts, ibytCuts, ipktCuts)
it was an existing error, but only in like the last few days on dev

2016-11-03 19:41 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModel.scala
> +    val flowWordCreator = new FlowWordCreator(timeCuts, ibytCuts, ipktCuts)
and only for netflow

2016-11-03 19:51 UTC, brandon-edwards commented on spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowScoreFunction.scala
> +    /** A null value for srcTopicMix or dstTopicMix indicated the ip (source or dest respectively)
Yes, I agree, I'll put that in.

2016-11-03 20:00 UTC, brandon-edwards commented on spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowScoreFunction.scala
> +    /** A null value for srcTopicMix or dstTopicMix indicated the ip (source or dest respectively)
Done

2016-11-03 20:27 UTC, rabarona approved these changes

2016-11-03 20:51 UTC, merged