Juliasantos/spark lda
Open-Network-Insight/open-network-insight pull request #127
Opened 2016-11-10 20:00 UTC by juliasantos

Adding in switched SparkLDA code. Default is LDAC, but you can set the ldaImplementation option in ml_ops.sh to be SparkLDA and switch back and forth.

2016-11-10 22:11 UTC, rabarona requested changes
Spark LDA looks great. I think we need to handle the implementation of multiple options for LDA so users don't have to send everything all the time.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/ml_ops.sh
> +LDA_IMP="LDAC"
Ideally, users shouldn't edit ml_ops.sh for setting parameters. 
I think TOPIC_COUNT was left there because it's a default and is not expected to be modified by users right now (cc: @NathanSegerlind ). I'd recommend putting this parameter in spot.conf so users can set as part of their installation.

Additionally,  if users can decide between one and the other would be great to update spot-ml installation guide with the possible values for LDA_IMP and let them know that if they go for SPARK LDA then they don't need MPI and all the extra configuration Spot-lda-c implies.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/ml_ops.sh
> +  --ldaImplementation ${LDA_IMP}
I'm thinking, do we need to keep sending mpi/spot-lda-c parameters when users select Spark LDA? 
--model
--topicdoc
--topicword
--ldapath
--mpicmd
--proccount
--nodes

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +             modelFile: String,
Do we need to keep modelFile, topicDocumentFile, topicWordFile, localPath, ldaPath, localUser and dataSource? 
I did a quick search of those and I don't see them being used in the code.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    //distinctDocument.cache()
Please remove unused code.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +        //.collect
Please remove unused code.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    //****Spark LDA implementation****
You can add scaladocs format with 

```
/**
*
*/
```

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    val numWordsInDocs = docWordCount.count.toInt
I did a search of numWordsInDocs usage and I didn't find anything. Do we need to keep this variable?

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    println("Running Spark LDA with params alpha = " + ldaAlpha + " beta = " + ldaBeta + " Max iters = " + maxIterations + " Optimizer = " + ldaOptimizer)
Please implement logger.info() instead of println. Logger is being passed to each pipeline:

`case "flow" => FlowSuspiciousConnectsAnalysis.run(config, sparkContext, sqlContext, logger)
          case "dns" => DNSSuspiciousConnectsAnalysis.run(config, sparkContext, sqlContext, logger)
          case "proxy" => ProxySuspiciousConnectsAnalysis.run(config, sparkContext, sqlContext, logger)`

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    for (topic <- Range(0, topicCount)) {
Do users need to see values?

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    println("Spark LDA Log likelihood: " + avgLogLikelihood)
Please use logger instead of println.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SuspiciousConnectsArgumentParser.scala
> +    opt[String]("ldaImplementation").required().valueName("< LDAC | sparkLDA >").
If we make a custom call in ml_ops.sh for the application when Spark LDA is selected, some of the parameters here need to be optional.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/dns/model/DNSSuspiciousConnectsModel.scala
> +    if(config.ldaImplementation == "LDAC") {
I'd replace if statement with case match to check LDAC -> Spot LDA C, <Spark Option> -> Spark LDA or default -> just error out. Including flow, dns and proxy.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +  def minMax(a: Array[Int]) : (Int, Int) = {
I did a quick search for minMax but couldn't find any usage.

2016-11-10 22:11 UTC, rabarona commented on spot-ml/src/test/scala/org/apache/spot/SpotSparkLDAWrapperTest.scala
> +class SpotSparkLDAWrapperTest extends TestingSparkContextFlatSpec with Matchers{
Please add unit testing for wordMatToMap.

2016-11-10 23:22 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/dns/model/DNSSuspiciousConnectsModel.scala
> +    if(config.ldaImplementation == "LDAC") {
Sorry, to make sure I understand...you want me to change the names of the options and make it a switch statement (case) instead of if?

2016-11-10 23:22 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/SuspiciousConnectsArgumentParser.scala
> +    opt[String]("ldaImplementation").required().valueName("< LDAC | sparkLDA >").
Are we making a custom call? My mindset was that the switch was for extended testing.

2016-11-10 23:22 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +  def minMax(a: Array[Int]) : (Int, Int) = {
Removed

2016-11-10 23:22 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    for (topic <- Range(0, topicCount)) {
More for our information as I was testing. Removed.

2016-11-10 23:22 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    val numWordsInDocs = docWordCount.count.toInt
Was informational at one point. Removed.

2016-11-10 23:22 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +             modelFile: String,
Removed

2016-11-10 23:22 UTC, juliasantos commented on spot-ml/ml_ops.sh
> +  --ldaImplementation ${LDA_IMP}
Assumption was that when LDA-C was removed, the parameters would be removed...

2016-11-10 23:25 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/SuspiciousConnectsArgumentParser.scala
> +    opt[String]("ldaImplementation").required().valueName("< LDAC | sparkLDA >").
Yeah no, we already decided the experimental branch thing. Nothing related with ml_ops.sh and args parser should be considered.

2016-11-10 23:29 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    println("Running Spark LDA with params alpha = " + ldaAlpha + " beta = " + ldaBeta + " Max iters = " + maxIterations + " Optimizer = " + ldaOptimizer)
Added logger to Spark LDA wrapper, still not used in LDA-C wrapper (not added)

2016-11-10 23:29 UTC, rabarona commented on spot-ml/src/main/scala/org/apache/spot/dns/model/DNSSuspiciousConnectsModel.scala
> +    if(config.ldaImplementation == "LDAC") {
No need to change names, _LDAC_ is fine, just define a value for Spark LDA, like SparkLDA and yes, a case match so you can add a default option which would be when nothing matches LDAC or SparkLDA.

2016-11-10 23:31 UTC, rabarona commented on spot-ml/ml_ops.sh
> +  --ldaImplementation ${LDA_IMP}
Yes, this comment was not having in mind experimental branch.

2016-11-11 00:34 UTC, NathanSegerlind commented on spot-ml/ml_ops.sh
> +LDA_IMP="LDAC"
I have discussed this with Nate Smith recently and this is pretty much what he is doing in his new conf file and ml_ops that he is writing

2016-11-11 00:37 UTC, NathanSegerlind commented on spot-ml/ml_ops.sh
> +  --ldaImplementation ${LDA_IMP}
even if lda-c stays, maybe we could have some root name from which all the other lda-c temp files (model, topicdoc, topicword) get their names...

but hopefully it doesn't stay

2016-11-11 00:40 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    //distinctDocument.cache()
i think he means the code in the comments

2016-11-11 00:43 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    //****Spark LDA implementation****
scaladoc is for autogenerating documentation for classes and methods...

non-Scaladoc scala comments are
/*
 *  coment goes here
 */
like old school C

2016-11-11 00:46 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    val testDupWords: RDD[(Long, Int)] = docWordCount.map({case SpotSparkLDAInput(doc, word, count) => (docStrToID(doc).toLong, wordDictionary(word))})
how expensive is this step?  it's a reasonable validation, test step for the inputs,
but if it's not nearly-free, maybe it should go into some kind of unit or regression test to catch bugs like that when testing, but not at every run of the program

2016-11-11 00:51 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    if ( ldaSeedLong != -1 ) lda.setSeed(ldaSeedLong)
what does it use for a seed if we don't set it?  (ie. ldaSeedLong == -1)

2016-11-11 00:52 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    val testDupWords: RDD[(Long, Int)] = docWordCount.map({case SpotSparkLDAInput(doc, word, count) => (docStrToID(doc).toLong, wordDictionary(word))})
I had already removed it...I don't think it's necessary anymore.

2016-11-11 00:54 UTC, juliasantos commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +    if ( ldaSeedLong != -1 ) lda.setSeed(ldaSeedLong)
Default is the hash value of the class name.

2016-11-11 00:55 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/SpotSparkLDAWrapper.scala
> +  /*
scaladoc here

/**
- doc
  */

2016-11-11 01:02 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/proxy/ProxySuspiciousConnectsModel.scala
> +      val SpotLDACOutput(documentResults, wordResults) = SpotLDACWrapper.runLDA(docWordCount,
it seems like we could push this if-check inside a new routine (called LDA) and that way we would have the if-check in one place and not in all three SuspiciousConnectsModels

2016-11-11 01:05 UTC, NathanSegerlind commented on spot-ml/src/main/scala/org/apache/spot/proxy/ProxySuspiciousConnectsModel.scala
> +  def ipWordCountFromDFSpark(sc: SparkContext,
what's with the distinction? everything in the ML routines is wrtitten in spark
maybe a name change and some scaladoc explaining the difference....

2016-11-14 06:19 UTC, closed without merging